const fs = require('fs');
const path = 'js/stickman_render_v61.js';

// Idempotency: skip if already rewritten (chunk helper is unique to chibi version)
const existing = fs.readFileSync(path, 'utf8');
if (existing.includes('function chunk(fill, lw)')) {
  console.log('stickman_render_v61.js already rewritten, skipping');
  process.exit(0);
}
// Also refuse if file is in unexpected state (original headR=1.7 line missing)
if (!existing.includes('headR = headR * 1.7')) {
  console.error('stickman_render_v61.js is in unexpected state — cannot safely apply rewrite');
  process.exit(1);
}

// Rewrite drawStickWeaponV61 with chibi proportions
// Weapons sized relative to headR (head radius) for "big head, big weapon, tiny body" chibi look
// At L1 headR≈10: sword~18px, shield~14px, bow~18px, spear~30px, cannon~18px
let content = fs.readFileSync(path, 'utf8');

// First, remove the 1.7x hack
content = content.replace("  headR = headR * 1.7; // v60 兼容:武器 scale 需 ~0.95×9.8≈9.3px，headR 仅 ~10px，放大 1.7 倍匹配\n", "");

// Find drawStickWeaponV61 function boundaries
const lines = content.split('\n');
let start = -1, end = -1;
for (let i = 0; i < lines.length; i++) {
  if (lines[i].includes('function drawStickWeaponV61(ctx, weapon, headR,')) start = i;
  if (start > 0 && end < 0 && i > start + 150 && lines[i].trim() === '}') end = i;
}
console.log('Weapon function: lines', start, 'to', end);

const newWeaponFunc = [
'function drawStickWeaponV61(ctx, weapon, headR, dir, hands, strike, fighting, accent, ink, weaponRole) {',
'  const { rx, ry, lx, ly, shX, shY } = hands;',
'  accent = accent || \'#8a6b46\';',
'  ink = ink || \'#40513c\';',
'  const k = strike || 0;',
'  ctx.lineCap = \'round\'; ctx.lineJoin = \'round\';',
'',
'  // chunk: fill + stroke 一次完成(需要预先 beginPath/closePath)',
'  function chunk(fill, lw) { ctx.save(); ctx.globalAlpha = 0.35; ctx.fillStyle = fill; ctx.fill(); ctx.restore(); ctx.strokeStyle = ink; ctx.lineWidth = lw; ctx.stroke(); }',
'',
'  // ═══════════ 盾 (tank) ═══════════',
'  // 大圆盾盖住躯干,半径≈头直径的 0.7 倍',
'  if (weapon === \'shield\') {',
'    const shieldR = headR * 1.4;                          // L1≈14px,遮住躯干',
'    const bash = k * headR * 0.6;                          // 盾击前顶',
'    const sx = shX + dir * (headR * 0.5 + bash);',
'    const sy = shY + headR * 0.6;',
'    ctx.save(); ctx.translate(sx, sy); ctx.scale(dir, 1);',
'    // 外环(木质)',
'    ctx.beginPath(); ctx.arc(0, 0, shieldR, 0, Math.PI * 2);',
'    ctx.strokeStyle = accent; ctx.lineWidth = headR * 0.3; ctx.stroke();',
'    // 内盘(半透队色)',
'    ctx.fillStyle = ink.replace(\'0.9)\', \'0.25)\').replace(\'#\', \'rgba(\');',
'    if (ctx.fillStyle === ink) ctx.fillStyle = \'rgba(120,120,120,0.25)\';',
'    ctx.beginPath(); ctx.arc(0, 0, shieldR * 0.85, 0, Math.PI * 2); ctx.fill();',
'    // 十字星标',
'    ctx.strokeStyle = ink; ctx.lineWidth = headR * 0.18;',
'    ctx.beginPath(); ctx.moveTo(0, -shieldR * 0.55); ctx.lineTo(0, shieldR * 0.55); ctx.stroke();',
'    ctx.beginPath(); ctx.moveTo(-shieldR * 0.55, 0); ctx.lineTo(shieldR * 0.55, 0); ctx.stroke();',
'    ctx.fillStyle = accent; ctx.beginPath(); ctx.arc(0, 0, headR * 0.18, 0, Math.PI * 2); ctx.fill();',
'    // 盾击波纹',
'    if (k > 0.3) {',
'      ctx.strokeStyle = \'rgba(255,255,255,0.55)\'; ctx.lineWidth = headR * 0.12;',
'      ctx.beginPath(); ctx.arc(shieldR * 0.7, 0, headR * (0.25 + (1 - k) * 0.7), -0.8, 0.8); ctx.stroke();',
'    }',
'    ctx.restore();',
'  }',
'',
'  // ═══════════ 枪 (front) ═══════════',
'  // 长杆+菱形枪头,总长≈头直径×2.5,有纵深感',
'  else if (weapon === \'spear\') {',
'    const thrust = k * headR * 1.2;                        // 突刺延伸',
'    ctx.save(); ctx.translate(rx, ry); ctx.rotate(0.12 * dir); ctx.scale(dir, 1); ctx.translate(thrust, 0);',
'    // 枪杆(木质长杆)',
'    const shaftLen = headR * 1.3;',
'    ctx.strokeStyle = accent; ctx.lineWidth = headR * 0.2; ctx.lineCap = \'round\';',
'    ctx.beginPath(); ctx.moveTo(-shaftLen * 0.4, 0); ctx.lineTo(shaftLen, 0); ctx.stroke();',
'    // 菱形枪头',
'    const headW = headR * 0.35, headL = headR * 0.7;',
'    ctx.beginPath();',
'    ctx.moveTo(shaftLen, -headW);',
'    ctx.lineTo(shaftLen + headL, 0);',
'    ctx.lineTo(shaftLen, headW);',
'    ctx.closePath();',
'    ctx.fillStyle = \'rgba(220,220,230,0.9)\'; ctx.fill();',
'    ctx.strokeStyle = ink; ctx.lineWidth = headR * 0.12; ctx.stroke();',
'    // 红缨穗',
'    ctx.fillStyle = \'#e04040\'; ctx.beginPath();',
'    ctx.arc(shaftLen - headR * 0.08, 0, headR * 0.2, 0, Math.PI * 2); ctx.fill();',
'    // 枪尖高光',
'    if (k > 0.2) {',
'      ctx.strokeStyle = \'rgba(255,255,255,0.8)\'; ctx.lineWidth = headR * 0.08;',
'      ctx.beginPath(); ctx.moveTo(shaftLen + headL * 0.5, -headW * 0.3);',
'      ctx.lineTo(shaftLen + headL * 0.9, 0); ctx.stroke();',
'    }',
'    ctx.restore();',
'  }',
'',
'  // ═══════════ 剑 (rush) ═══════════',
'  // 宽刃弯刀,刃长≈头直径×0.9,厚实可爱',
'  else if (weapon === \'sword\') {',
'    const bladeLen = headR * 1.8;                          // L1≈18px',
'    const bladeW = headR * 0.35;',
'    const ang = 0.12 + k * 2.0;                             // 后引→前劈弧',
'    ctx.save(); ctx.translate(rx, ry); ctx.scale(dir, 1); ctx.rotate(ang);',
'    // 刀身(弯月形)',
'    ctx.beginPath();',
'    ctx.moveTo(0, -bladeW);',
'    ctx.quadraticCurveTo(bladeLen * 0.5, -bladeW * 1.1, bladeLen, -bladeW * 0.15);',
'    ctx.lineTo(bladeLen, bladeW * 0.15);',
'    ctx.quadraticCurveTo(bladeLen * 0.5, bladeW * 1.1, 0, bladeW);',
'    ctx.closePath();',
'    // 金属渐变',
'    const grad = ctx.createLinearGradient(0, -bladeW, 0, bladeW);',
'    grad.addColorStop(0, \'rgba(255,255,250,0.95)\');',
'    grad.addColorStop(0.4, \'rgba(210,210,220,0.9)\');',
'    grad.addColorStop(1, \'rgba(150,150,170,0.8)\');',
'    ctx.fillStyle = grad; ctx.fill();',
'    ctx.strokeStyle = ink; ctx.lineWidth = headR * 0.16; ctx.stroke();',
'    // 十字护手',
'    ctx.strokeStyle = accent; ctx.lineWidth = headR * 0.16; ctx.lineCap = \'round\';',
'    ctx.beginPath(); ctx.moveTo(-bladeLen * 0.05, -bladeW * 1.5); ctx.lineTo(-bladeLen * 0.05, bladeW * 1.5); ctx.stroke();',
'    // 握柄',
'    ctx.strokeStyle = accent; ctx.lineWidth = headR * 0.2;',
'    ctx.beginPath(); ctx.moveTo(-bladeLen * 0.25, 0); ctx.lineTo(-bladeLen * 0.05, 0); ctx.stroke();',
'    // 挥砍残影(3条渐淡弧)',
'    if (k > 0.15) {',
'      for (let g = 0; g < 3; g++) {',
'        ctx.globalAlpha = (1 - k) * (0.35 - g * 0.1);',
'        ctx.strokeStyle = \'rgba(255,255,240,0.7)\'; ctx.lineWidth = headR * 0.15 * (1 - g * 0.25);',
'        ctx.beginPath(); ctx.arc(0, 0, bladeLen * (0.7 + g * 0.15), -0.3 + g * 0.15, 0.9 + k * 1.2 + g * 0.12); ctx.stroke();',
'      }',
'      ctx.globalAlpha = 1;',
'    }',
'    ctx.restore();',
'  }',
'',
'  // ═══════════ 弓 (back/control/support) ═══════════',
'  // 反曲弓,弓弧直径≈头直径×1.2,弦和箭清晰可见',
'  else if (weapon === \'bow\') {',
'    const bowR = headR * 1.2;                              // 弓弧半径,L1≈12px',
'    const drawDist = fighting ? (k > 0.03 ? (1 - k) * headR * 0.7 : headR * 0.8) : headR * 0.15;',
'    ctx.save(); ctx.translate(lx, ly); ctx.scale(dir, 1);',
'    // 弓身(粗弧)',
'    ctx.strokeStyle = accent; ctx.lineWidth = headR * 0.28; ctx.lineCap = \'round\';',
'    ctx.beginPath(); ctx.arc(0, 0, bowR, -1.2, 1.2); ctx.stroke();',
'    // 弓端回钩',
'    const tipL = { x: Math.cos(-1.2) * bowR, y: Math.sin(-1.2) * bowR };',
'    const tipR = { x: Math.cos(1.2) * bowR, y: Math.sin(1.2) * bowR };',
'    ctx.lineWidth = headR * 0.14;',
'    ctx.beginPath(); ctx.moveTo(tipL.x, tipL.y); ctx.lineTo(tipL.x + headR * 0.25, tipL.y - headR * 0.18); ctx.stroke();',
'    ctx.beginPath(); ctx.moveTo(tipR.x, tipR.y); ctx.lineTo(tipR.x - headR * 0.25, tipR.y - headR * 0.18); ctx.stroke();',
'    // 弓弦(双线,更明显)',
'    ctx.strokeStyle = \'rgba(200,180,160,0.85)\'; ctx.lineWidth = headR * 0.08;',
'    ctx.beginPath(); ctx.moveTo(tipL.x, tipL.y); ctx.lineTo(-drawDist, 0); ctx.lineTo(tipR.x, tipR.y); ctx.stroke();',
'    // 搭箭(拉弦时箭杆+箭头+箭羽)',
'    if (fighting && k > 0.03) {',
'      const ax = bowR * 0.25 + (1 - k) * headR * 1.6;     // 箭尾位置(从弓向外)',
'      const arrowLen = headR * 1.4;',
'      // 箭杆',
'      ctx.strokeStyle = ink; ctx.lineWidth = headR * 0.12;',
'      ctx.beginPath(); ctx.moveTo(ax, 0); ctx.lineTo(ax + arrowLen, 0); ctx.stroke();',
'      // 箭头(三角)',
'      ctx.fillStyle = \'rgba(200,200,210,0.9)\';',
'      ctx.beginPath(); ctx.moveTo(ax + arrowLen, 0); ctx.lineTo(ax + arrowLen * 0.7, -headR * 0.22); ctx.lineTo(ax + arrowLen * 0.7, headR * 0.22); ctx.closePath(); ctx.fill();',
'      // 箭羽(尾部十字)',
'      ctx.strokeStyle = \'rgba(255,255,255,0.7)\'; ctx.lineWidth = headR * 0.08;',
'      ctx.beginPath(); ctx.moveTo(ax, -headR * 0.2); ctx.lineTo(ax - headR * 0.2, 0); ctx.stroke();',
'      ctx.beginPath(); ctx.moveTo(ax, headR * 0.2); ctx.lineTo(ax - headR * 0.2, 0); ctx.stroke();',
'    }',
'    ctx.restore();',
'  }',
'',
'  // ═══════════ 炮 (siege) ═══════════',
'  // 粗炮管+炮口环+后膛,有重量感,双手扛',
'  else if (weapon === \'cannon\') {',
'    const recoil = k * headR * 0.5;                        // 后坐力',
'    const mx = (rx + lx) / 2 - dir * recoil;',
'    const my = (ry + ly) / 2 + headR * 0.3;',
'    const barrelLen = headR * 1.6;                         // L1≈16px 炮管长',
'    const barrelW = headR * 0.45;                           // 炮管半宽',
'    // 身体到炮的连接线',
'    ctx.strokeStyle = ink; ctx.lineWidth = headR * 0.22; ctx.lineCap = \'round\';',
'    ctx.beginPath(); ctx.moveTo(shX, shY); ctx.lineTo(mx, my); ctx.stroke();',
'    ctx.save(); ctx.translate(mx, my); ctx.scale(dir, 1); ctx.rotate(-0.06);',
'    // 炮身主体',
'    ctx.beginPath();',
'    ctx.moveTo(-headR * 0.3, -barrelW);',
'    ctx.lineTo(barrelLen, -barrelW);',
'    ctx.arc(barrelLen, 0, barrelW, -Math.PI / 2, Math.PI / 2);',
'    ctx.lineTo(-headR * 0.3, barrelW);',
'    ctx.closePath();',
'    ctx.fillStyle = \'rgba(80,65,55,0.9)\'; ctx.fill();',
'    ctx.strokeStyle = ink; ctx.lineWidth = headR * 0.18; ctx.stroke();',
'    // 炮口环(加粗)',
'    ctx.beginPath(); ctx.arc(barrelLen, 0, barrelW * 1.2, 0, Math.PI * 2);',
'    ctx.strokeStyle = ink; ctx.lineWidth = headR * 0.16; ctx.stroke();',
'    // 后膛方块',
'    ctx.fillStyle = \'rgba(60,50,40,0.8)\';',
'    ctx.fillRect(-headR * 0.5, -barrelW * 1.1, headR * 0.3, barrelW * 2.2);',
'    ctx.strokeStyle = ink; ctx.lineWidth = headR * 0.1;',
'    ctx.strokeRect(-headR * 0.5, -barrelW * 1.1, headR * 0.3, barrelW * 2.2);',
'    // 小轮子(两侧)',
'    ctx.fillStyle = \'rgba(100,85,70,0.8)\';',
'    ctx.beginPath(); ctx.arc(-headR * 0.1, barrelW * 1.0, headR * 0.2, 0, Math.PI * 2); ctx.fill();',
'    ctx.beginPath(); ctx.arc(-headR * 0.1, -barrelW * 1.0, headR * 0.2, 0, Math.PI * 2); ctx.fill();',
'    // 炮口火光',
'    if (k > 0.4) {',
'      const flashR = headR * (0.2 + (1 - k) * 1.0);',
'      const flashAlpha = k * 0.9;',
'      ctx.fillStyle = k > 0.65 ? \'rgba(255,240,100,\' + flashAlpha + \')\' : \'rgba(255,150,40,\' + flashAlpha + \')\';',
'      ctx.beginPath(); ctx.arc(barrelLen + headR * 0.2, 0, flashR, 0, Math.PI * 2); ctx.fill();',
'    }',
'    ctx.restore();',
'  }',
'',
'  // ═══════════ 法杖 (control 兼容) ═══════════',
'  else if (weapon === \'staff\') {',
'    ctx.save(); ctx.translate(rx, ry); ctx.scale(dir, 1); ctx.rotate(0.5 - k * 0.25);',
'    ctx.strokeStyle = ink; ctx.lineWidth = headR * 0.2;',
'    ctx.beginPath(); ctx.moveTo(-headR * 0.3, 0); ctx.lineTo(headR * 1.3, 0); ctx.stroke();',
'    ctx.beginPath(); ctx.arc(headR * 1.4, 0, headR * 0.35, 0, Math.PI * 2);',
'    chunk(accent, headR * 0.2);',
'    if (k > 0.3) {',
'      ctx.strokeStyle = accent; ctx.globalAlpha = k; ctx.lineWidth = headR * 0.12;',
'      ctx.beginPath(); ctx.arc(headR * 1.4, 0, headR * (0.5 + (1 - k) * 1.0), 0, Math.PI * 2); ctx.stroke();',
'      ctx.globalAlpha = 1;',
'    }',
'    ctx.restore();',
'  }',
'',
'  // ═══════════ 空手 (merge) ═══════════',
'  else if (weapon === \'none\' && fighting) {',
'    ctx.fillStyle = ink;',
'    ctx.beginPath(); ctx.arc(rx, ry, headR * 0.18, 0, Math.PI * 2); ctx.fill();',
'    ctx.beginPath(); ctx.arc(lx, ly, headR * 0.18, 0, Math.PI * 2); ctx.fill();',
'  }',
'}',
];

lines.splice(start, end - start + 1, ...newWeaponFunc);
fs.writeFileSync(path, lines.join('\n'));
console.log('Weapon function fully rewritten');
